name: CI-CD Pipeline - School Portal

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t school-portal:test .

      - name: Test Health Check
        run: echo "Build successful"
